---
bootstrap_motd: false

## Packages to install for motd
motd_packages:
  - fastfetch

## Path to cron.hourly script
motd_cron_script: /etc/cron.hourly/motd

## Paths for motd/issue output
motd_issue_dir: /etc/issue.d
motd_issue_file: fastfetch.issue

motd_motd_dir: /etc/motd.d
motd_motd_file: fastfetch
