---
bootstrap_ntp: false

timezone: "Etc/UTC"
ntp_servers:
  - time.google.com
ntp_fallback_servers:
  - ntp.ubuntu.com
  - 0.ru.pool.ntp.org
  - 1.ru.pool.ntp.org
  - 2.ru.pool.ntp.org
  - 3.ru.pool.ntp.org

ntp_root_distance_max_sec: 5
ntp_poll_interval_min_sec: 32
ntp_poll_interval_max_sec: 2048
