---
- name: Install motd packages
  ansible.builtin.package:
    name: "{{ motd_packages }}"
    state: present
  check_mode: false

- name: Ensure issue.d directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - "{{ motd_issue_dir }}"
    - "{{ motd_dir }}"

- name: Deploy motd cron.hourly script
  ansible.builtin.template:
    src: motd.j2
    dest: "{{ motd_cron_script }}"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o="
