---
# Variables
- name: Load a variable file based on the OS type, or a default if not found.
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution_release | lower }}.yml"
        - default.yml
      paths:
        - "vars/{{ ansible_os_family | lower }}"

- name: Install motd packages
  ansible.builtin.package:
    name: "{{ motd_packages }}"
    state: present
  check_mode: false

- name: Ensure issue.d directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ motd_dir }}"
    - "{{ motd_issue_dir }}"

- name: Deploy motd cron.hourly script
  ansible.builtin.template:
    src: motd.j2
    dest: "{{ motd_cron_script }}"
    owner: root
    group: root
    mode: "0750"
